name: linus playground
favicon: null
layout_spectrum: 0.308558
typography_spectrum: 0.572072
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#71695e'
    - '#8d9693'
    - '#b4bdbc'
    - '#29200f'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
